import { defineConfig, presetAttributify, presetIcons, presetWind3, transformerDirectives, transformerVariantGroup } from 'unocss'

export default defineConfig({
  shortcuts: [
    ['fc', 'flex items-center justify-center'],
    ['apple-nav', 'bg-[rgba(0,0,0,0.8)] text-white backdrop-blur-[20px] backdrop-saturate-[180%]'],
    ['apple-nav-shell', 'sticky top-0 z-50 border-b border-white/10 apple-nav'],
    ['apple-nav-icon', 'fc h-7 w-7 rounded-full text-white/76 no-underline transition-colors duration-200 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus'],
    ['apple-link', 'inline-flex items-center gap-1 rounded-full text-[14px] leading-[1.43] tracking-[-0.224px] text-accentstrong no-underline transition-colors duration-200 hover:text-accent hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus'],
    ['apple-link-dark', 'inline-flex items-center gap-1 rounded-full text-[14px] leading-[1.43] tracking-[-0.224px] text-accentdark no-underline transition-colors duration-200 hover:text-white hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus'],
    ['apple-cta', 'inline-flex items-center justify-center rounded-full border border-transparent bg-accent px-5 py-[10px] text-[17px] leading-[1] tracking-normal text-white no-underline transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus disabled:cursor-not-allowed disabled:opacity-50'],
    ['apple-cta-dark', 'inline-flex items-center justify-center rounded-full border border-white/28 bg-transparent px-5 py-[10px] text-[17px] leading-[1] tracking-normal text-white no-underline transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus disabled:cursor-not-allowed disabled:opacity-50'],
    ['apple-filter', 'appearance-none inline-flex items-center justify-center rounded-full border border-transparent bg-surfacesoft px-4 py-3 text-[14px] leading-[1.29] tracking-[-0.224px] text-inksoft transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus disabled:cursor-not-allowed disabled:opacity-50'],
    ['apple-display-hero', 'text-[40px] font-display font-600 leading-[1.08] tracking-[-0.28px] sm:text-[56px]'],
    ['apple-display-section', 'text-[32px] font-display font-600 leading-[1.1] tracking-[-0.24px] sm:text-[40px]'],
    ['apple-display-stage', 'text-[32px] font-display font-600 leading-[1.08] tracking-[-0.24px] sm:text-[40px] sm:tracking-normal'],
    ['apple-tile-title', 'text-[28px] font-display leading-[1.14] tracking-[0.196px]'],
    ['apple-card-title', 'text-[21px] font-display font-700 leading-[1.19] tracking-[0.231px]'],
    ['apple-body-copy', 'text-[17px] leading-[1.47] tracking-[-0.374px]'],
    ['apple-body-copy-muted', 'apple-body-copy text-inksoft'],
    ['apple-body-compact', 'text-[17px] font-600 leading-[1.24] tracking-[-0.374px]'],
    ['apple-caption', 'text-[14px] leading-[1.43] tracking-[-0.224px]'],
    ['apple-caption-muted', 'apple-caption text-inksoft'],
    ['apple-kicker', 'text-[12px] leading-[1.33] tracking-[0.14em] uppercase'],
    ['apple-micro', 'text-[12px] leading-[1.33] tracking-[-0.12px]'],
    ['apple-card', 'rounded-[24px] bg-surface px-5 py-6 shadow-card'],
    ['apple-card-wide', 'rounded-[24px] bg-surface px-6 py-7 shadow-card'],
    ['apple-panel', 'rounded-[28px] bg-surface px-5 py-6 shadow-card sm:px-6 sm:py-7'],
    ['apple-filter-button', 'apple-filter min-h-[48px] px-4 text-center'],
    ['apple-stage-shell', 'rounded-[28px] bg-page-dark px-4 py-6 sm:px-8 sm:py-8'],
    ['apple-dark-chip', 'inline-flex items-center rounded-full border border-white/12 bg-white/6 px-3 py-1.5 text-[12px] leading-[1.33] tracking-[-0.12px]'],
    ['apple-dark-chip-status', 'apple-dark-chip gap-2'],
    ['theme-toggle-group', 'relative inline-flex items-center gap-1 rounded-full bg-white/8 p-1'],
    ['theme-toggle-indicator', 'pointer-events-none absolute left-1 top-1 h-7 w-7 rounded-full bg-white shadow-[0_1px_3px_rgba(0,0,0,0.24)] transition-transform duration-250 ease-out'],
    ['theme-toggle-option', 'relative z-[1] fc h-7 w-7 rounded-full text-white/76 transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus'],
    ['theme-toggle-option-active', '!text-black hover:!text-black'],
    ['theme-icon-stroke', 'h-3.5 w-3.5 fill-none stroke-current stroke-2'],
    ['theme-icon-fill', 'h-3.5 w-3.5 fill-current'],
  ],
  presets: [
    presetWind3(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  theme: {
    colors: {
      'page': 'var(--page)',
      'page-dark': 'var(--page-dark)',
      'surface': 'var(--surface)',
      'surfacesoft': 'var(--surface-soft)',
      'surface-dark': 'var(--surface-dark)',
      'surface-dark-2': 'var(--surface-dark-2)',
      'line': 'var(--line)',
      'line-strong': 'var(--line-strong)',
      'muted': 'var(--muted)',
      'inksoft': 'var(--ink-soft)',
      'ink': 'var(--ink)',
      'code': 'var(--code-bg)',
      'accent': 'var(--accent)',
      'accentstrong': 'var(--accent-strong)',
      'accentdark': 'var(--accent-dark)',
      'focus': 'var(--focus)',
      'overlay': 'var(--overlay)',
    },
    boxShadow: {
      card: 'var(--shadow)',
    },
    fontFamily: {
      sans: 'var(--font-body)',
      body: 'var(--font-body)',
      display: 'var(--font-display)',
      mono: 'var(--font-mono)',
    },
  },
})
